// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hugsinvtfaftypzavpml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Z3NpbnZ0ZmFmdHlwemF2cG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDUwNTcsImV4cCI6MjA2MjgyMTA1N30.gf4N6h1ANCI74569P1nFc-0_wyi_XdMN_jdx5ZSIhRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);